#!/data/data/com.termux/files/usr/bin/bash
clear
unset LD_PRELOAD
dir=`pwd`
if  [ $dir != $HOME/PAYLOAD-INJECTION ]
	then
		dir=$HOME/PAYLOAD INJECTI
    #figlet -f mini ..........PAYLOAD-INJECTION...........
    echo -e "$green
                               .___.
          /)               ,-^     ^-.
         //               / -         \
.-------| |--------------/  __     __  \-------------------._____.| 
|PAYLOAD-IN| |>>>>>>>>>>>>>| />>\   />>\ |>>>>>>>>>>>>>>TARGET:>  |
         \\               \    /|\    /
          \)               \   \_/   /
                            |       |
                            |+a+p+k+|
                            \       /
                             ^-----^
                             
echo
echo -e "$blue               ~~~~~~~~~~~~~~~~~~~~~~~~~~" 
echo -e "$red                  PAYLOAD-INJECTION v-1.0"
echo -e "$blue              ~~~~~~~~~~~~~~~~~~~~~~"~~~~~" 
 figlet -f mini   ................ Coming soon...............
echo 
echo -e "$red    ~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
echo -e "$blue     My email > saunaksingha88@gmail.com 
echo -e "$blue     Channel name > Technical Saunak
echo -e "$blue    Note:For any problems tell me on email 
echo -e "$blue    Sorry :I am new in github for any wrong code,please tell me
echo -e "$blue    Please : please subscribe my channel 
echo -e "$blue    My inspiration > Hax4us youtube channel 
echo -e "$blue       thanks for install 
echo -e "$red   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
echo -e "$blue        thank you 
echo
;;
esac
