#!/data/data/com.termux/files/usr/bin/bash
clear
unset LD_PRELOAD
dir=`pwd`
if  [ $dir != $HOME/PAYLOAD-INJECTION ]
	then
		dir=$HOME/PAYLOAD INJECTI
    #figlet -f mini ..........PAYLOAD-INJECTION...........
    echo -e "$green
                               .___.
          /)               ,-^     ^-.
         //               / -         \
.-------| |--------------/  __     __  \-------------------._____.| 
|PAYLOAD-IN| |>>>>>>>>>>>>>| />>\   />>\ |>>>>>>>>>>>>>>TARGET:>  |
         \\               \    /|\    /
          \)               \   \_/   /
                            |       |
                            |+a+p+k+|
                            \       /
                             ^-----^
                             
echo
echo -e "$blue               ~~~~~~~~~~~~~~~~~~~~~~~~~~" 
echo -e "$red                  PAYLOAD-INJECTION v-1.0"
echo -e "$blue              ~~~~~~~~~~~~~~~~~~~~~~"~~~~~" 
 figlet - f mini   ................ Coming soon................ 
